name: 🔧 Template Adaptation
description: Share industry-specific adaptation
title: "[ADAPTATION] "
labels: ["community", "adaptation"]
body:
  - type: dropdown
    attributes:
      label: Which template was adapted?
      options:
        - RAG Assessment Card
        - NTSR Innovation Tracker
        - Role Responsibility Matrix
        - Team Readiness Assessment
        - Weekly Retrospective Guide
        - Emergence Mapping
        - Decision Latency Tracker
        - Multiple templates
  - type: textarea
    attributes:
      label: For which industry/domain?
      placeholder: e.g., IT, education, healthcare, finance, etc.
  - type: textarea
    attributes:
      label: Adaptation description
      placeholder: What changes did you make? How did you adapt it for your domain?
  - type: textarea
    attributes:
      label: Results and benefits
      placeholder: What improvements did the adaptation bring?
  - type: textarea
    attributes:
      label: Additional materials (optional)
      placeholder: Links to examples, screenshots, documents
