name: Template Adaptation
description: Share industry adaptation
title: "[ADAPTATION] "
labels: ["adaptation"]
body:
  - type: textarea
    attributes:
      label: Which template did you adapt?
    validations:
      required: true
  - type: textarea
    attributes:
      label: For which industry?
    validations:
      required: true
