name: 🐛 Сообщение об ошибке
description: Сообщить об ошибке в шаблоне
title: "[ОШИБКА] "
labels: ["bug", "triage"]
body:
  - type: dropdown
    attributes:
      label: Какой шаблон?
      options:
        - RAG Assessment Card
        - NTSR Innovation Tracker
        - Role Responsibility Matrix
        - Team Readiness Assessment
        - Weekly Retrospective Guide
        - Emergence Mapping
        - Decision Latency Tracker
  - type: textarea
    attributes:
      label: Описание проблемы
      placeholder: Что именно работает не так?
  - type: textarea
    attributes:
      label: Ожидаемое поведение
      placeholder: Как должно работать?
