name: 🐛 Bug Report
description: Report a template bug
title: "[BUG] "
labels: ["bug", "triage"]
body:
  - type: dropdown
    attributes:
      label: Which template?
      options:
        - RAG Assessment Card
        - NTSR Innovation Tracker
        - Role Responsibility Matrix
        - Team Readiness Assessment
        - Weekly Retrospective Guide
        - Emergence Mapping
        - Decision Latency Tracker
  - type: textarea
    attributes:
      label: Problem description
      placeholder: What exactly is not working?
  - type: textarea
    attributes:
      label: Expected behavior
      placeholder: How should it work?
