name: 💡 Feature Request
description: Предложить улучшение шаблона
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: dropdown
    attributes:
      label: Для какого шаблона?
      options:
        - RAG Assessment Card
        - NTSR Innovation Tracker
        - Role Responsibility Matrix
        - Team Readiness Assessment
        - Weekly Retrospective Guide
        - Emergence Mapping
        - Decision Latency Tracker
        - Все шаблоны
        - Новая функциональность
  - type: textarea
    attributes:
      label: Описание предложения
      placeholder: Какое улучшение вы предлагаете?
  - type: textarea
    attributes:
      label: Ожидаемая польза
      placeholder: Как это улучшит работу с шаблонами?
